spring:
  profiles:
    active: "dev"
  main:
    banner-mode: "off"
  jmx:
    default-domain: upload
  data:
    mongodb:
      host: localhost
      port: 27017
      database: estate
server:
  port: 8080
  servlet:
    context-path: /data-service

---
spring:
  profiles: dev
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
      resolve-lazily: true
---
spring:
  profiles: test
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
      resolve-lazily: true
---
spring:
  profiles: prod


